//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompAgri
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.User = new HashSet<User>();
            this.UserProfilePermission = new HashSet<UserProfilePermission>();
        }
    
        public int UserProfile_Id { get; set; }
        public string ProfileName { get; set; }
        public Nullable<bool> CanLikeContributorConnection { get; set; }
        public bool CanDeleteOtherPeopleConnection { get; set; }
        public bool CanDownloadFullLog { get; set; }
    
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<UserProfilePermission> UserProfilePermission { get; set; }
    }
}
