//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompAgri
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfilePermission
    {
        public int UserProfilePermission_Id { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public Nullable<bool> Allow { get; set; }
        public Nullable<bool> Deny { get; set; }
        public int UserProfile_Id { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
